from collections import OrderedDict

DEFAULT_EXPORT_FORMAT = "json"  # "json" "xml"

SPACED_STARTS = ["addrUI", "output", "notification", "adj"]

FILE_NAME_TO_CLASSES = OrderedDict([('TObjectsPoint', ["PpoPoint"]),
                                    ('TObjectsSignal', ["PpoRoutePointer",
                                                        "PpoTrainSignal",
                                                        "PpoShuntingSignal",
                                                        "PpoShuntingSignalWithTrackAnD",
                                                        "PpoFictionalSignal",
                                                        "PpoWarningSignal",
                                                        "PpoRepeatSignal",
                                                        "PpoGroupTrainSignal",
                                                        "PpoFictionalRepeatingShuntingSignal",
                                                        "PpoInterstationWaySignal",
                                                        "PpoInterstationWayFictionalSignal",
                                                        "PpoIndicationSignal"]),
                                    ('TObjectsTrack', ["PpoTrackAnD",
                                                       "PpoAnDtrack",
                                                       "PpoTrackAnDwithPoint",
                                                       "PpoLineEnd",
                                                       "PpoPointSection",
                                                       "PpoTrackSection",
                                                       "PpoInterstationWayTrack",
                                                       "PpoIndicationTrack"]),
                                    ('IObjectsCodeGenerator', ["PpoCodeEnablingRelayALS",
                                                               "PpoCodeGeneratorALS"]),
                                    ('IObjectsEncodingPoint', ["PpoTrackEncodingPoint"]),
                                    ('IObjectsPoint', ["PpoPointMachineCi"]),
                                    ('IObjectsRelay', ["PpoGeneralPurposeRelayInput",
                                                       "PpoGeneralPurposeRelayOutput",
                                                       "PpoGeneralPurposeRelayTranslator",
                                                       "PpoSignalRelayRepeater",
                                                       "PpoTrackRelayRepeater",
                                                       "PpoGeneralPurposeGroupRelayInput"]),
                                    ('IObjectsSignal', ["PpoLightSignalCi",
                                                        "PpoRoutePointerRi",
                                                        "PpoLightSignalRi"]),
                                    ('IObjectsTrack', ["PpoTrackReceiverCi",
                                                       "PpoTrackReceiverRi",
                                                       "PpoTrackUnit"]),
                                    ('Border', ["PpoControlAreaBorder",
                                                "PpoAutomaticBlockingSystem",
                                                "PpoSemiAutomaticBlockingSystem",
                                                "PpoAdjacentStationTrainSignal",
                                                "PpoInterstationWayBorder",
                                                "PpoAutomaticBlockingSystemRi",
                                                "PpoAdjacentStationTrainSignalRi",
                                                "PpoSemiAutomaticBlockingSystemRi",
                                                "PpoInterstationWayBorderRi"]),
                                    ('Equipment', ["PpoControlDeviceDerailmentStock",
                                                   "PpoControlDeviceDerailmentStockCi",
                                                   "PpoElectricHeating",
                                                   "PpoElectricHeatingRi"]),
                                    ('Operator', ["TrafficOperatorWorkset",
                                                  "StationOperatorWorkset",
                                                  "ControlArea"]),
                                    ('RailWarningArea', ["PpoRailCrossingRi",
                                                         "PpoTrainNotificationRi",
                                                         "PpoRailCrossing",
                                                         "PpoTrackCrossroad",
                                                         "PpoGroupRailFittersWarningArea",
                                                         "PpoRailFittersWarningAreaRi",
                                                         "PpoRailFittersWarningArea",
                                                         "PpoInterstationWayCrossroad"]),
                                    ('Telesignalization', ["PpoCabinetUsoBk",
                                                           "PpoInsulationResistanceMonitoring",
                                                           "PpoPointMachinesCurrentMonitoring",
                                                           "PpoTelesignalization",
                                                           "PpoIndicationGroupTrackSensors",
                                                           "PpoPointsMonitoring",
                                                           "PpoLightModeRi",
                                                           "PpoLightMode",
                                                           "PpoEncodingUnitsMonitoring",
                                                           "PpoTrackSensorsMonitoring",
                                                           "PpoFireAndSecurityAlarm",
                                                           "PpoDieselGenerator"])])

MAIN_CLASSES_TREE = OrderedDict([("INTERFACE OBJECTS", OrderedDict([("IF_LightSignal", ["PpoLightSignalCi",
                                                                                        "PpoLightSignalRi"]),
                                                                    ("IF_RoutePointer", ["PpoRoutePointerRi"]),
                                                                    ("IF_Point", ["PpoPointMachineCi"]),
                                                                    ("IF_AB", ["PpoAutomaticBlockingSystemRi"]),
                                                                    ("IF_PAB", ["PpoSemiAutomaticBlockingSystemRi"]),
                                                                    ("IF_InterBorder", ["PpoInterstationWayBorderRi"]),
                                                                    ("IF_AdjTrainSignal",
                                                                     ["PpoAdjacentStationTrainSignalRi"]),
                                                                    ("IF_CrossRoad", ["PpoRailCrossingRi",
                                                                                      "PpoTrainNotificationRi"]),
                                                                    ("IF_Fitters", ["PpoRailFittersWarningAreaRi"]),
                                                                    (
                                                                        "IF_Derail",
                                                                        ["PpoControlDeviceDerailmentStockCi"]),
                                                                    ("IF_Track", ["PpoTrackReceiverCi",
                                                                                  "PpoTrackReceiverRi"]),
                                                                    ("IF_Coding", ["PpoCodeEnablingRelayALS",
                                                                                   "PpoTrackEncodingPoint",
                                                                                   "PpoCodeGeneratorALS"]),
                                                                    ("IF_Relay", ["PpoGeneralPurposeRelayInput",
                                                                                  "PpoGeneralPurposeRelayOutput",
                                                                                  "PpoGeneralPurposeRelayTranslator",
                                                                                  "PpoSignalRelayRepeater",
                                                                                  "PpoTrackRelayRepeater",
                                                                                  "PpoGeneralPurposeGroupRelayInput"]),
                                                                    ("IF_PointService", ["PpoElectricHeatingRi"])])),
                                 ("TECHNOLOGY OBJECTS", OrderedDict([("TH_Zone", ["PpoControlAreaBorder"]),
                                                                     ("TH_Signal", ["PpoTrainSignal",
                                                                                    "PpoFictionalSignal",
                                                                                    "PpoWarningSignal",
                                                                                    "PpoRepeatSignal",
                                                                                    "PpoShuntingSignal",
                                                                                    "PpoGroupTrainSignal",
                                                                                    "PpoFictionalRepeatingShuntingSignal",
                                                                                    "PpoInterstationWaySignal",
                                                                                    "PpoInterstationWayFictionalSignal",
                                                                                    "PpoIndicationSignal"]),
                                                                     ("TH_RoutePointer", ["PpoRoutePointer"]),
                                                                     ("TH_Track", ["PpoPointSection",
                                                                                   "PpoTrackSection",
                                                                                   "PpoTrackAnD",
                                                                                   "PpoAnDtrack",
                                                                                   "PpoLineEnd",
                                                                                   "PpoInterstationWayTrack",
                                                                                   "PpoIndicationTrack"]),
                                                                     ("TH_Point", ["PpoPoint"]),
                                                                     ("TH_AB", ["PpoAutomaticBlockingSystem"]),
                                                                     ("TH_PAB", ["PpoSemiAutomaticBlockingSystem"]),
                                                                     ("TH_InterBorder", ["PpoInterstationWayBorder"]),
                                                                     ("TH_AdjTrainSignal",
                                                                      ["PpoAdjacentStationTrainSignal"]),
                                                                     ("TH_CrossRoad", ["PpoTrackCrossroad",
                                                                                       "PpoRailCrossing"]),
                                                                     ("TH_InterCrossRoad",
                                                                      ["PpoInterstationWayCrossroad"]),
                                                                     ("TH_GroupFitters",
                                                                      ["PpoGroupRailFittersWarningArea"]),
                                                                     ("TH_Fitters", ["PpoRailFittersWarningArea"]),
                                                                     ("TH_Derail", ["PpoControlDeviceDerailmentStock"]),
                                                                     ("TH_Coding", ["PpoTrackUnit",
                                                                                    "PpoTrackEncodingPoint"]),
                                                                     ("TH_PointService", ["PpoElectricHeating"])])),
                                 ("ADJACENT POINT CLASSES",
                                  OrderedDict([("AP_ShSignal", ["PpoShuntingSignalWithTrackAnD"]),
                                               ("AP_TrackAND", ["PpoTrackAnDwithPoint"])])),
                                 ("ROUTE CLASSES", OrderedDict([("RT_TrainRoute", ["TrainRoute"]),
                                                                ("RT_ShuntingRoute", ["ShuntingRoute"])])),
                                 ("OPERATOR CLASSES", OrderedDict([("OP_Control", ["TrafficOperatorWorkset",
                                                                                   "StationOperatorWorkset",
                                                                                   "ControlArea"])])),
                                 ("TS CLASSES", OrderedDict([("TS_UsoBk", ["PpoCabinetUsoBk"]),
                                                             ("TS_Point", ["PpoInsulationResistanceMonitoring",
                                                                           "PpoPointMachinesCurrentMonitoring",
                                                                           "PpoPointsMonitoring"]),
                                                             ("TS_TS", ["PpoTelesignalization"]),
                                                             ("TS_Light", ["PpoLightModeRi",
                                                                           "PpoLightMode"]),
                                                             ("TS_Fire", ["PpoFireAndSecurityAlarm"]),
                                                             ("TS_DG", ["PpoDieselGenerator"]),
                                                             ("TS_Coding", ["PpoEncodingUnitsMonitoring",
                                                                            "PpoTrackSensorsMonitoring"]),
                                                             ("TS_IndicGroup", ["PpoIndicationGroupTrackSensors"])]))
                                 ])

TPL_TO_OBJ_ID = OrderedDict([('PpoPoint', "Str"),
                             ('PpoTrainSignal', "SvP"),
                             ('PpoShuntingSignal', "SvM"),
                             ('PpoPointSection', "SPU"),
                             ('PpoTrackSection', "SPU"),
                             ('PpoTrackAnD', "Put"),
                             ('PpoAutomaticBlockingSystem', "AdjAB"),
                             ('PpoSemiAutomaticBlockingSystem', "AdjPAB"),
                             ('PpoLineEnd', "Tpk"),
                             ('PpoControlAreaBorder', "GRU")])

DEFAULT_AUTO_ADD_IO = True
DEFAULT_SIGNAL_I_TYPE = "Ci"
DEFAULT_POINT_I_TYPE = "Ci"
DEFAULT_DERAIL_I_TYPE = "Ci"

ONE_LINE_HEIGHT = 28

SINGLE_ATTRIBUTE_PROPERTIES = "SINGLE_ATTRIBUTE_PROPERTIES"
NAMED_ATTRIBUTE_PROPERTIES = "NAMED_ATTRIBUTE_PROPERTIES"
ADDRESS = "ADDRESS"
PROPERTIES = "PROPERTIES"
INTERNAL_STRUCTURE = "INTERNAL_STRUCTURE"

LINE_EDIT_STYLESHEET = ("color: black;"
                        "background-color: white;"
                        "selection-color: yellow;"
                        "selection-background-color: blue;")

DEFAULT_ADDRESS_SUGGESTION = "USO:::"
# print(len(CONFIG_FILE_JSON_NAMES))
# print(len(FILE_NAME_TO_CLASSES))
